#!/usr/bin/env bash
# Install load balancer HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 32391-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 32391-web-01 18.235.249.155:80 check\n\tserver 32391-web-02 18.204.20.140:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
