#!/usr/bin/env bash
# A script that pings an IP address that is passed as an argument

if [ "$#" -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	IP=$1
	ping -c 5 "$IP"
fi
